#!/bin/bash
# USAGE: test_connection HOST PORT [CCEMAIL]
# DESCRIPTION:
#  This script will continuously attempt to open a TCP connection
#  to the specified host and port. When the connection succeeds,
#  an email will be sent out and the program will terminate. This
#  is especially useful in an environment where someone else is
#  doing your network change, or if you're testing something out
#  and don't want to waste time actively watching a server.
#
#  TODO:
#     * Allow one to specify TIMEOUT and SLEEP_TIME via argument
#     * Show usage
#     * Ability to inverse logic, so show when a port is closed
#     * Ability to keep the program running after email is sent

trap '' HUP
DEFAULT_EMAIL=youremail@example.com
TIMEOUT=5
SLEEP_TIME=10

dest_host=$1
dest_port=$2
ccEmail=$3

shortHostname=$(hostname -s)

while true ; do
   nc -vzw$TIMEOUT `echo $dest_host $dest_port`
   if [ $? -eq 0 ] ; then
      echo "We can hit $dest_host:$dest_port from $shortHostname now." | mail -s "Test success: $shortHostname -> $dest_host:$dest_port" $DEFAULT_EMAIL,$ccEmail
      break
   fi  
   sleep $SLEEP_TIME
done

